kind: pipeline
name: gotest
steps:
 - name: first_step
   image: golang:1.13.1
   commands:
    - go get -v -t ./...
# - name: second_step
#   image: golang:1.13.1
#   commands:
#    - go vet ./...
# - name: third_step
#   image: golang:1.13.1
#   commands:
#    - go test -v -race ./...
 - name: telegram
   image: appleboy/drone-telegram
   when:
    status:
      - success
      - failure
   settings: 
      token: 
        from_secret: TELEGRAM_TOKEN
      to: 302394045
trigger:
  branch:
    - main
  event:
    - push